# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50e464845d5dce6646e3b95e44437305fc6fc6edd991c3ccc2c02a09ef7b6b1d27e7aa8c0421524185a75170e34f397f2ea3b6d0b5175ead76b5dbaaf0afcb7e

test:
  secret_key_base: 7d646f23c39ec39b09ce1e79880296358fadb4fea7441943acee762add3e5600bf3ac1b7f83739195c6f63ade43a6113935d495d482fdaeb643b2a4cb6f6ff1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
